spring.application.name=TranslatorText
spring.r2dbc.url=r2dbc:pool:postgresql://aws-0-us-west-1.pooler.supabase.com:5432/postgres
spring.r2dbc.username=postgres.trbmsmhgpanpcvbpktey
spring.r2dbc.password=t02translatortext